#Criar um workflow disarado por um evento de 'push'

name: "Exercicio 1"

on:
  push:
  
jobs:
  print_date_ubuntu:
    name: Print date Ubuntu!
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Ubuntu!
        run: date
      
  print_date_windows:
    name: Print date Windows!
    runs-on: windows-latest
    
    steps:
      - name: Print Windows!
        run: date
        
  print_date_macos:
    name: Print MacOs!
    runs-on: macos-latest
    
    steps:
      - name: Print MacOS!
        run: date
       
  print_date_fim:
    name: Print date final!
    runs-on: ubuntu-latest
    
    needs:
      - print_date_ubuntu
      - print_date_windows
      - print_date_macos
      
    steps:
      - name: Print date final!
        run: date
    
  

